
client: main.o camera.o opengl.o vector.o application.o model.o system.o texture.o
	gcc -o client main.o


application.o: ./src/application.cpp
	gcc -c ./src/application.cpp

camera.o: ./src/camera.cpp
	gcc -c ./src/camera.cpp

model.o: ./src/model.cpp
	gcc -c ./src/model.cpp

system.o: ./src/system.cpp
	gcc -c ./src/system.cpp

texture.o: ./src/texture.cpp
	gcc -c ./src/texture.cpp


main.o: ./src/main.cpp
	gcc -c ./src/main.cpp


opengl.o: ./src/opengl.cpp
	gcc -c ./src/opengl.cpp

vector.o: ./src/vector.cpp
	gcc -c ./src/vector.cpp
